import type { GoalItem } from "./types";

export const INITIAL_GOALS: GoalItem[] = [
  {
    id: "goal-1",
    title: "Increase organic traffic from international visitors",
    period: "90 days",
    avgProgress: 33,
    status: "Active",
    trafficGrowthTarget: "+40%",
    primaryConversion: "Signup",
    budget: "$1,000.00 USD",
    targetQualifiedVisits: "12,000",
    kpis: [
      {
        id: "kpi-1-1",
        name: "Organic traffic",
        type: "traffic",
        baseline: "42,000",
        current: "51,200",
        target: "58,800",
        progressPercentage: 54.8,
        progressRatioText: "51,200 / 58,800",
      },
      {
        id: "kpi-1-2",
        name: "Qualified visits",
        type: "visits",
        baseline: "8,000",
        current: "9,600",
        target: "12,000",
        progressPercentage: 80,
        progressRatioText: "9,600 / 12,000",
      },
      {
        id: "kpi-1-3",
        name: "Signups",
        type: "signups",
        baseline: "420",
        current: "510",
        target: "700",
        progressPercentage: 73,
        progressRatioText: "510 / 700",
      },
    ],
  },
  {
    id: "goal-2",
    title: "Boost Southeast Asia self-serve signups",
    period: "60 days",
    avgProgress: 33,
    status: "Active",
    trafficGrowthTarget: "+30%",
    primaryConversion: "Self-serve Signup",
    budget: "$850.00 USD",
    targetQualifiedVisits: "9,500",
    kpis: [
      {
        id: "kpi-2-1",
        name: "Regional SEA traffic",
        type: "traffic",
        baseline: "25,000",
        current: "31,400",
        target: "36,000",
        progressPercentage: 58.2,
        progressRatioText: "31,400 / 36,000",
      },
      {
        id: "kpi-2-2",
        name: "Self-serve visits",
        type: "visits",
        baseline: "5,500",
        current: "7,200",
        target: "9,500",
        progressPercentage: 75.8,
        progressRatioText: "7,200 / 9,500",
      },
      {
        id: "kpi-2-3",
        name: "Self-serve accounts",
        type: "signups",
        baseline: "220",
        current: "310",
        target: "450",
        progressPercentage: 68.9,
        progressRatioText: "310 / 450",
      },
    ],
  },
  {
    id: "goal-3",
    title: "Expand local merchant partner acquisitions",
    period: "45 days",
    avgProgress: 33,
    status: "Draft",
    trafficGrowthTarget: "+15%",
    primaryConversion: "Partner Onboarded",
    budget: "$500.00 USD",
    targetQualifiedVisits: "3,000",
    kpis: [
      {
        id: "kpi-3-1",
        name: "Partner portal visitors",
        type: "traffic",
        baseline: "1,200",
        current: "1,650",
        target: "2,400",
        progressPercentage: 37.5,
        progressRatioText: "1,650 / 2,400",
      },
      {
        id: "kpi-3-2",
        name: "Merchant inquiries",
        type: "visits",
        baseline: "90",
        current: "140",
        target: "200",
        progressPercentage: 70,
        progressRatioText: "140 / 200",
      },
      {
        id: "kpi-3-3",
        name: "Signed partners",
        type: "signups",
        baseline: "15",
        current: "24",
        target: "40",
        progressPercentage: 60,
        progressRatioText: "24 / 40",
      },
    ],
  },
];
