import type { MemberItem } from "./types";

export const INITIAL_MEMBERS: MemberItem[] = [
  {
    id: "m-1",
    name: "Nguyen Van Minh",
    isYou: true,
    subtitle: "Workspace creator",
    email: "minh@tripc.vn",
    role: "Owner",
    status: "Active",
    joined: "Jan 12, 2026",
    avatarBg: "#2563eb",
    initials: "NM",
  },
  {
    id: "m-2",
    name: "Tran Thi Lan",
    isYou: false,
    subtitle: "Growth Lead",
    email: "lan@tripc.vn",
    role: "Editor",
    status: "Active",
    joined: "Feb 03, 2026",
    avatarBg: "#6366f1",
    initials: "TL",
  },
  {
    id: "m-3",
    name: "Le Hoang Nam",
    isYou: false,
    subtitle: "Content Strategist",
    email: "nam@tripc.vn",
    role: "Editor",
    status: "Active",
    joined: "Mar 18, 2026",
    avatarBg: "#10b981",
    initials: "LN",
  },
  {
    id: "m-4",
    name: "Anna Wilson",
    isYou: false,
    subtitle: "External Auditor",
    email: "anna@example.com",
    role: "Viewer",
    status: "Active",
    joined: "Apr 02, 2026",
    avatarBg: "#475569",
    initials: "AW",
  },
];
