import type { KnowledgeSource, SourceCategory } from "./types";

export const CATEGORY_OPTIONS: SourceCategory[] = [
  "Company",
  "Pricing",
  "FAQ",
  "Brand",
  "Policy",
  "Products",
  "Services",
];

export const INITIAL_SOURCES: KnowledgeSource[] = [
  {
    id: "s-1",
    name: "TripC company overview.pdf",
    subtitle: "v1 · 3 chunks",
    category: "Company",
    type: "PDF",
    status: "Approved",
    added: "Oct 08, 2026",
  },
  {
    id: "s-2",
    name: "Pricing and packages.pdf",
    subtitle: "v1 · Ingesting embeddings",
    category: "Pricing",
    type: "PDF",
    status: "Processing",
    added: "Oct 08, 2026",
  },
  {
    id: "s-3",
    name: "TripC FAQ",
    subtitle: "https://tripc.vn/faq · 12 chunks",
    category: "FAQ",
    type: "URL",
    status: "Approved",
    added: "Oct 05, 2026",
  },
  {
    id: "s-4",
    name: "Brand guidelines",
    subtitle: "v1 · 4 chunks",
    category: "Brand",
    type: "Text",
    status: "Imported",
    added: "Oct 04, 2026",
  },
  {
    id: "s-5",
    name: "Cancellation policy.pdf",
    subtitle: "v1 · 2 chunks",
    category: "Policy",
    type: "PDF",
    status: "Needs review",
    added: "Oct 04, 2026",
  },
  {
    id: "s-6",
    name: "Da Nang tour catalogue.pdf",
    subtitle: "v1 · 8 chunks",
    category: "Products",
    type: "PDF",
    status: "Approved",
    added: "Sep 29, 2026",
  },
  {
    id: "s-7",
    name: "https://tripc.vn/experiences",
    subtitle: "Crawled page · 15 chunks",
    category: "Services",
    type: "URL",
    status: "Approved",
    added: "Sep 24, 2026",
  },
  {
    id: "s-8",
    name: "Customer onboarding guide.pdf",
    subtitle: "v2 · 6 chunks",
    category: "Company",
    type: "PDF",
    status: "Approved",
    added: "Sep 20, 2026",
  },
  {
    id: "s-9",
    name: "Hotel partner agreements.pdf",
    subtitle: "v1 · 9 chunks",
    category: "Policy",
    type: "PDF",
    status: "Approved",
    added: "Sep 18, 2026",
  },
  {
    id: "s-10",
    name: "https://tripc.vn/about",
    subtitle: "Crawled page · 5 chunks",
    category: "Company",
    type: "URL",
    status: "Approved",
    added: "Sep 15, 2026",
  },
  {
    id: "s-11",
    name: "Support ticket templates",
    subtitle: "v1 · 3 chunks",
    category: "Services",
    type: "Text",
    status: "Imported",
    added: "Sep 12, 2026",
  },
  {
    id: "s-12",
    name: "Seasonal promotional guidelines.pdf",
    subtitle: "v1 · 4 chunks",
    category: "Pricing",
    type: "PDF",
    status: "Needs review",
    added: "Sep 10, 2026",
  },
  {
    id: "s-13",
    name: "Airport transfer rates.pdf",
    subtitle: "v1 · 2 chunks",
    category: "Pricing",
    type: "PDF",
    status: "Processing",
    added: "Sep 08, 2026",
  },
  {
    id: "s-14",
    name: "https://tripc.vn/blog/da-nang-food-guide",
    subtitle: "Crawled page · 18 chunks",
    category: "Products",
    type: "URL",
    status: "Approved",
    added: "Sep 05, 2026",
  },
  {
    id: "s-15",
    name: "Villa rental standard rules.pdf",
    subtitle: "v1 · 7 chunks",
    category: "Policy",
    type: "PDF",
    status: "Approved",
    added: "Sep 01, 2026",
  },
  {
    id: "s-16",
    name: "Local guide handbook",
    subtitle: "v2 · 11 chunks",
    category: "Brand",
    type: "Text",
    status: "Imported",
    added: "Aug 28, 2026",
  },
  {
    id: "s-17",
    name: "https://tripc.vn/contact",
    subtitle: "Crawled page · 2 chunks",
    category: "FAQ",
    type: "URL",
    status: "Approved",
    added: "Aug 25, 2026",
  },
  {
    id: "s-18",
    name: "Emergency contact procedures.pdf",
    subtitle: "v1 · 3 chunks",
    category: "Policy",
    type: "PDF",
    status: "Needs review",
    added: "Aug 20, 2026",
  },
  {
    id: "s-19",
    name: "Private yacht charter packages.pdf",
    subtitle: "v1 · 5 chunks",
    category: "Products",
    type: "PDF",
    status: "Approved",
    added: "Aug 15, 2026",
  },
  {
    id: "s-20",
    name: "Digital nomad housing perks",
    subtitle: "v1 · 4 chunks",
    category: "Company",
    type: "Text",
    status: "Imported",
    added: "Aug 10, 2026",
  },
  {
    id: "s-21",
    name: "Merchant verification checklist",
    subtitle: "v1 · 8 chunks",
    category: "Company",
    type: "Text",
    status: "Imported",
    added: "Aug 05, 2026",
  },
  {
    id: "s-22",
    name: "Expat coworking spaces directory",
    subtitle: "v1 · 6 chunks",
    category: "Services",
    type: "Text",
    status: "Imported",
    added: "Aug 01, 2026",
  },
  {
    id: "s-23",
    name: "Local culinary tour brief",
    subtitle: "v1 · 5 chunks",
    category: "Products",
    type: "Text",
    status: "Imported",
    added: "Jul 28, 2026",
  },
  {
    id: "s-24",
    name: "Local supplier contract template",
    subtitle: "v1 · 5 chunks",
    category: "Services",
    type: "Text",
    status: "Processing",
    added: "Jul 22, 2026",
  },
];
